### ISSUE TITLE
NSE post tiff images

### ISSUE THREAD

**Issue by gaborcsardi** [mailund/r-programmer-blog#2]
Tiffs do not  show in my browser (latest Chome), maybe convert them to GIFs  or PNGs?

![screen shot 2018-09-20 at 11 09 01 pm](https://user-images.githubusercontent.com/660288/45849568-51981e80-bd2a-11e8-8145-0d7b2b003177.png)

I'll  try to install some Chrome plugin, nevertheless....

**Comment by mailund** [comment]
I can convert the files. The app I used for drawing them uses tiff and Safari had no problem showing them so I thought that was ok. Will update the files
